#! /bin/sh

songinforeturn=$(song_info)
if [ $? -eq 0 ]; then
  songinfo=" $songinforeturn │"
else
  songinfo=""
fi
nettrafreturn=$(nettraf)
if [ $nettrafreturn -z ]; then
  nettrafficinfo=""
else
  nettrafficinfo=" $nettrafreturn │"
fi

netstatusreturn=$(netStatus)
if [ $netstatusreturn = "false" ]; then
  netstatusinfo=" OFFLINE │"
else
  netstatusinfo=""
fi

echo "$songinfo$netstatusinfo$nettrafficinfo RAM `ramUsage`% │ `temperature`°C │ VOL `volumeInfo`% │ `datum` │ `timeInfo`"
