#! /bin/sh

files="$@"

if [ "$1" = "--dry-run" ]; then
	echo "--dry-run disables actual renaming and just shows you the result if it was actually done"
fi

for file in ${files[@]}
do
	if ! [ -d "$file" ]; then
	if [ -f "$file" ]; then

		# eg .jpg from iPhone 7 Plus
		datetime="$(file "$file" | grep "datetime=" | sed "s/.*datetime=//g;s/].*//g;s/://g;s/ /_/g;s/,.*//g")"

		if [ -z $datetime ]; then
			# eg .MOV from iPhone 7 Plus
			datetime="$(exiftool -time:all "$file" | grep "Creation"  | sed "s/.* ://g;s/^ //g;s/ /_/g;s/://g;s/.*e//g;s/+.*//g")"
		fi

		filename=$(basename -- "$file")
		dirname=$(dirname -- "$file")

		extension="${filename##*.}"
		extensionString=""

		# if there is no extension
		if [ $extension = $filename ]; then
			extensionString=""
		else
			extensionString=".$extension"
		fi

		newfilename="${datetime}${extensionString}"
		counter=$((1))

		while [ -f "$dirname/$newfilename" ]
		do
			newfilename="${datetime}_${counter}${extensionString}"
			counter=$((counter+1))
		done
		
		if [ "$1" = "--dry-run" ]; then
			echo "From: "$file""
		        echo "To  : "$dirname/$newfilename""
			echo ""
		else
			mv -n "$file" "$dirname/$newfilename"
		fi
	else
		if ! [ "$1" = "--dry-run" ]; then
			echo "\"$file\" does not exist"
		fi
	fi
	fi
done

