#! /bin/bash

if [ -z $1 ]; then
	echo 'First parameter must be fps (eg \"30\")'
fi;

if [ -z $2 ]; then
	echo 'Second parameter must be the starting frame number (eg \"1\")'
fi

if [ -z $3 ]; then
	echo 'Third parameter must be the file extension of the sequence images (eg \"png\")'
fi

if [ -z $4 ]; then
	echo 'Fourth parameter must be the output file name without file extension (eg \"output\")'
	exit
fi

ffmpeg -framerate "$1" -start_number "$2" -i %04d."$3" -c:v libx264 -pix_fmt yuv420p -vf "crop=trunc(iw/2)*2:trunc(ih/2)*2" "$3.mp4"
