#! /bin/sh
temperatures=$(sensors -u | grep "temp1_input:" | sed "s/\s*temp1_input: //g" | wc -l)
avgtemp=$(echo "scale=10;($(sensors -u | grep "temp1_input:" | sed "s/\s*temp1_input: //g" | paste -sd"+"))/$temperatures" | bc)

printf "%.0f" $avgtemp
